# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'receitas-jacquenan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for receitas-jacquenan
  pod 'SwiftLint'

  target 'receitas-jacquenanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'receitas-jacquenanUITests' do
    # Pods for testing
  end

end
