disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - function_parameter_count
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Pods
 - receitas-jacquenanTests
 - receitas-jacquenanCoreDataTests
 - receitas-jacquenanUITests
line_length: 
  ignores_comments: true
  warning: 180
